general:
  project_name: segmentation
  logs_dir: logs
  saved_models_dir: saved_models
  gpu_memory_limit: 18
  global_seed: 127
  display_figures: false
  num_threads_tflite: 8

operation_mode: chain_tqe

model:
  model_type: deeplab
  model_name: st_deeplabv3_mnv2_a050_s16_asppv2
  input_shape: (416,416,3)
  pretrained: true

dataset:
  dataset_name: person_coco_2017_pascal_voc_2012
  class_names:
  - background
  - person
  training_path: ./datasets/person_COCO2017_VOC2012/JPEGImages
  training_masks_path: ./datasets/person_COCO2017_VOC2012/SegmentationClassAug
  training_files_path: ./datasets/person_COCO2017_VOC2012/ImageSets/Segmentation/trainaug.txt
  validation_path: ./datasets/person_COCO2017_VOC2012/JPEGImages
  validation_masks_path: ./datasets/person_COCO2017_VOC2012/SegmentationClassAug
  validation_files_path: ./datasets/person_COCO2017_VOC2012/ImageSets/Segmentation/val.txt
  quantization_split: 0.02
  prediction_path: /local/data/seg_coco_2017_pascal_voc_2012/coco_2017_pascal_voc_2012/pred

preprocessing:
  rescaling:
    scale: 1/127.5
    offset: -1
  resizing:
    aspect_ratio: fit
    interpolation: bilinear
  color_mode: rgb


data_augmentation:
  random_flip:
    mode: horizontal_and_vertical
  random_contrast:
    factor: 0.4
  random_brightness:
    factor: 0.3


training:
  frozen_layers: None
  dropout: 0.4
  batch_size: 32
  epochs: 400
  optimizer:
    Adam:
      learning_rate: 0.001
  callbacks:
    ReduceLROnPlateau:
      monitor: val_loss
      mode: min
      factor: 0.5
      patience: 20
      min_lr: 1.0e-06
    EarlyStopping:
      monitor: val_accuracy
      mode: max
      restore_best_weights: true
      patience: 80


quantization:
  quantizer: onnx_quantizer
  target_opset: 17
  granularity: per_channel
  quantization_type: PTQ
  quantization_input_type: float
  quantization_output_type: float
  export_dir: quantized_models
  onnx_extra_options:
    CalibMovingAverage: True


benchmarking:
  board: STM32N6570-DK


tools:
  stedgeai:
    optimization: balanced
    on_cloud: true
    path_to_stedgeai: C:/ST/STEdgeAI/<x.y>/Utilities/windows/stedgeai.exe
  path_to_cubeIDE: C:/ST/STM32CubeIDE_<*.*.*>/STM32CubeIDE/stm32cubeide.exe


mlflow:
  uri: ./tf/src/experiments_outputs/mlruns

  
hydra:
  run:
    dir: ./tf/src/experiments_outputs/${now:%Y_%m_%d_%H_%M_%S}
