general:
  project_name: human_activity_recognition
  model_path: null
  logs_dir: logs
  saved_models_dir: saved_models
  display_figures: false
  global_seed: 123
  gpu_memory_limit: 24
operation_mode: chain_tb
dataset:
  name: wisdm
  class_names:
  - Jogging
  - Stationary
  - Stairs
  - Walking
  training_path: ../datasets/WISDM_ar_v1.1/WISDM_ar_v1.1_raw.txt
  validation_path: null
  validation_split: 0.2
  test_path: null
  test_split: null
  seed: 123
preprocessing:
  gravity_rot_sup: true
  normalization: false
training:
  model:
    name: gmp
    input_shape: (24, 3, 1)
    pretrained_model_path: null
  resume_training_from: null
  dropout: 0.5
  batch_size: 256
  epochs: 200
  optimizer:
    Adam:
      learning_rate: 0.001
  callbacks:
    ReduceLROnPlateau:
      monitor: val_accuracy
      mode: max
      factor: 0.5
      patience: 40
      min_lr: 1.0e-05
    EarlyStopping:
      monitor: val_accuracy
      mode: max
      restore_best_weights: true
      patience: 60
tools:
  stedgeai:
    version: 10.0.0
    optimization: balanced
    on_cloud: True
    path_to_stedgeai: C:/Users/<XXXXX>/STM32Cube/Repository/Packs/STMicroelectronics/X-CUBE-AI/<*.*.*>/Utilities/windows/stedgeai.exe
  path_to_cubeIDE: C:/ST/STM32CubeIDE_1.17.0/STM32CubeIDE/stm32cubeide.exe
benchmarking:
  board: B-U585I-IOT02A
deployment:
  c_project_path: ../../application_code/sensing_thread_x/
  IDE: GCC
  verbosity: 1
  hardware_setup:
    serie: STM32U5
    board: B-U585I-IOT02A
mlflow:
  uri: ./experiments_outputs/mlruns
hydra:
  run:
    dir: ./experiments_outputs/${now:%Y_%m_%d_%H_%M_%S}
