general:
  project_name: Plant
  model_path: null
  logs_dir: logs
  saved_models_dir: saved_models
  global_seed: 127
  gpu_memory_limit: 10
operation_mode: chain_tqe
dataset:
  name: plant
  class_names: [Apple_scab,Apple_black_rot,Apple_cedar_apple_rust,Apple_healthy,Background_without_leaves,Blueberry_healthy,Cherry_powdery_mildew,Cherry_healthy,Corn_gray_leaf_spot,Corn_common_rust,Corn_northern_leaf_blight,Corn_healthy,Grape_black_rot,Grape_black_measles,Grape_leaf_blight,Grape_healthy,Orange_haunglongbing,Peach_bacterial_spot,Peach_healthy,Pepper_bacterial_spot,Pepper_healthy,Potato_early_blight,Potato_healthy,Potato_late_blight,Raspberry_healthy,Soybean_healthy,Squash_powdery_mildew,Strawberry_healthy,Strawberry_leaf_scorch,Tomato_bacterial_spot,Tomato_early_blight,Tomato_healthy,Tomato_late_blight,Tomato_leaf_mold,Tomato_septoria_leaf_spot,Tomato_spider_mites_two-spotted_spider_mite,Tomato_target_spot,Tomato_mosaic_virus,Tomato_yellow_leaf_curl_virus]
  training_path: ./datasets/Plant_leave_diseases_dataset_without_augmentation
  validation_path: null
  validation_split: 0.2
  test_path: null
  quantization_path: null
  quantization_split: null
  seed: 127
preprocessing:
  rescaling:
    scale: 1/127.5
    offset: -1
  resizing:
    interpolation: nearest
    aspect_ratio: fit
  color_mode: rgb
data_augmentation:
  random_contrast:
    factor: 0.2
  random_brightness:
    factor: 0.2
  random_flip:
    mode: horizontal_and_vertical
  random_translation:
    width_factor: 0.4
    height_factor: 0.3
    fill_mode: reflect
    interpolation: nearest
  random_rotation:
    factor: 0.25
    fill_mode: reflect
    interpolation: nearest
  random_zoom:
    width_factor: 0.3
    height_factor: 0.3
    fill_mode: reflect
    interpolation: nearest
training:
  model:
    name: squeezenet
    version: v11
    input_shape: (224, 224, 3)
  dropout: 0.5
  batch_size: 256
  epochs: 1000
  optimizer:
    Adam:
      learning_rate: 0.001
  callbacks:
    ReduceLROnPlateau:
      monitor: val_accuracy
      mode: max
      factor: 0.5
      patience: 40
      min_lr: 1.0e-05
    EarlyStopping:
      monitor: val_accuracy
      mode: max
      restore_best_weights: false
      patience: 60
quantization:
  quantizer: TFlite_converter
  quantization_type: PTQ
  quantization_input_type: uint8
  quantization_output_type: float
  export_dir: quantized_models
prediction:
  test_files_path: .
tools:
  stedgeai:
    version: 10.0.0
    optimization: balanced
    on_cloud: True
    path_to_stedgeai: C:/Users/<XXXXX>/STM32Cube/Repository/Packs/STMicroelectronics/X-CUBE-AI/<*.*.*>/Utilities/windows/stedgeai.exe
  path_to_cubeIDE: C:/ST/STM32CubeIDE_<*.*.*>/STM32CubeIDE/stm32cubeide.exe
benchmarking:
  board: STM32H747I-DISCO
deployment:
  c_project_path: ../application_code/image_classification/
  IDE: GCC
  verbosity: 1
  hardware_setup:
    serie: STM32H7
    board: STM32H747I-DISCO
    input: CAMERA_INTERFACE_DCMI
    output: DISPLAY_INTERFACE_USB
mlflow:
  uri: ./src/experiments_outputs/mlruns
hydra:
   run:
      dir: ./src/experiments_outputs/${now:%Y_%m_%d_%H_%M_%S}
