general:
  project_name: segmentation
  model_type: deeplab_v3
  logs_dir: logs
  saved_models_dir: saved_models
  gpu_memory_limit: 10
  global_seed: 127
  display_figures: false
  num_threads_tflite: 8
operation_mode: chain_tqe
dataset:
  name: pascal_voc_person
  class_names:
  - background
  - person
  training_path: ../datasets/person_COCO2017_VOC2012/JPEGImages
  training_masks_path: ../datasets/person_COCO2017_VOC2012/SegmentationClassAug
  training_files_path: ../datasets/person_COCO2017_VOC2012/ImageSets/Segmentation/trainaug.txt
  validation_path: ../datasets/person_COCO2017_VOC2012/JPEGImages
  validation_masks_path: ../datasets/person_COCO2017_VOC2012/SegmentationClassAug
  validation_files_path: ../datasets/person_COCO2017_VOC2012/ImageSets/Segmentation/val.txt
  quantization_split: 0.2
preprocessing:
  rescaling:
    scale: 1/127.5
    offset: -1
  resizing:
    aspect_ratio: fit
    interpolation: bilinear
  color_mode: rgb
data_augmentation:
  random_flip:
    mode: horizontal_and_vertical
  random_crop:
    crop_center_x: (0.25, 0.75)
    crop_center_y: (0.25, 0.75)
    crop_width: (0.6, 0.9)
    crop_height: (0.6, 0.9)
    change_rate: 0.6
  random_contrast:
    factor: 0.4
  random_brightness:
    factor: 0.3
training:
  model:
    name: mobilenet
    version: v2
    alpha: 0.5
    output_stride: 16
    input_shape: (416, 416, 3)
    pretrained_weights: imagenet
  frozen_layers: None
  dropout: 0.4
  batch_size: 32
  epochs: 400
  optimizer:
    Adam:
      learning_rate: 0.001
  callbacks:
    ReduceLROnPlateau:
      monitor: val_loss
      mode: min
      factor: 0.5
      patience: 20
      min_lr: 1.0e-06
    EarlyStopping:
      monitor: val_accuracy
      mode: max
      restore_best_weights: true
      patience: 80
quantization:
  quantizer: onnx_quantizer
  target_opset: 17
  granularity: per_channel
  quantization_type: PTQ
  quantization_input_type: float
  quantization_output_type: float
  extra_options: calib_moving_average
  export_dir: quantized_models
prediction:
  test_files_path: /local/data/seg_coco_2017_pascal_voc_2012/coco_2017_pascal_voc_2012/pred
benchmarking:
  board: STM32N6570-DK
tools:
  stedgeai:
    version: 10.0.0
    optimization: balanced
    on_cloud: true
    path_to_stedgeai: C:/Users/<XXXXX>/STM32Cube/Repository/Packs/STMicroelectronics/X-CUBE-AI/<*.*.*>/Utilities/windows/stedgeai.exe
  path_to_cubeIDE: C:/ST/STM32CubeIDE_1.17.0/STM32CubeIDE/stm32cubeide.exe
mlflow:
  uri: ./experiments_outputs/mlruns
hydra:
  run:
    dir: ./experiments_outputs/${now:%Y_%m_%d_%H_%M_%S}
