general:
  project_name: st_yoloxn_d067_w025_416_3_st_person
  logs_dir: logs
  saved_models_dir: saved_models
  display_figures: false
  gpu_memory_limit: 24
  num_threads_tflite: 24
  global_seed: 127

model:
  model_type: st_yoloxn
  model_name: st_yoloxn
  depth_mul: 0.67
  width_mul: 0.25
  input_shape: (416,416,3)
  pretrained: false

operation_mode: chain_tqe

dataset:
  dataset_name: custom_dataset
  class_names: [person] 
  format: tfs
  training_path: /local/data/od_st_person/train
  validation_path: /local/data/od_st_person/test
  test_path: /local/data/od_st_person/test
  quantization_path: /local/data/od_st_person/train
  quantization_split: 0.001

preprocessing:
  rescaling:
    scale: 1/255
    offset: 0
  resizing:
    aspect_ratio: fit
    interpolation: bilinear
  color_mode: rgb

data_augmentation:
  random_crop:
    crop_center_x: (0.25, 0.75)
    crop_center_y: (0.25, 0.75)
    crop_width: (0.6, 0.9)
    crop_height: (0.6, 0.9)
    change_rate: 0.5
  
  random_periodic_resizing:
    period: 20
    image_sizes:
    - (352, 352)
    - (384, 384)
    - (416, 416)
    - (448, 448)
    - (480, 480)
    - (512, 512)
    - (544, 544)
    - (576, 576)
  random_contrast:
    factor: 0.4
  random_brightness:
    factor: 0.3
  random_flip:
    mode: horizontal
  random_rotation:
    factor: 0.02
    fill_mode: wrap
    interpolation: nearest

training:
  dropout: null
  batch_size: 64
  epochs: 750
  optimizer:
    Adam:
      learning_rate: 0.0025
  callbacks:
    LRWarmupCosineDecay:
      initial_lr: 1.0e-05
      warmup_steps: 20
      max_lr: 0.001875
      hold_steps: 30
      decay_steps: 650
      end_lr: 1.0e-06
    EarlyStopping:
      monitor: val_map
      patience: 80
      restore_best_weights: true
      verbose: 1 

postprocessing:
  yolo_anchors: [0.5, 0.5, 0.07, 0.25, 0.23, 0.7]
  confidence_thresh: 0.001
  NMS_thresh: 0.5
  IoU_eval_thresh: 0.5
  plot_metrics: false
  max_detection_boxes: 100

quantization:
  quantizer: TFlite_converter
  quantization_type: PTQ
  quantization_input_type: uint8
  quantization_output_type: float
  export_dir: quantized_models

tools:
   stedgeai:
      optimization: balanced
      on_cloud: True
      path_to_stedgeai: C:/ST/STEdgeAI/<x.y>/Utilities/windows/stedgeai.exe
   path_to_cubeIDE: C:/ST/STM32CubeIDE_<*.*.*>/STM32CubeIDE/stm32cubeide.exe

benchmarking:
  board: STM32N6570-DK

mlflow:
   uri: ./tf/src/experiments_outputs/mlruns

hydra:
   run:
      dir: ./tf/src/experiments_outputs/${now:%Y_%m_%d_%H_%M_%S}
