general:
   model_path: ../../stm32ai-modelzoo/pose_estimation/movenet/ST_pretrainedmodel_public_dataset/custom_dataset_person_13kpts/st_movenetheatmaps_192/st_movenet_lightning_heatmaps_192.h5
   model_type: heatmaps_spe
   num_threads_tflite: 8

operation_mode: chain_eqeb

dataset:
   name: coco_pose
   keypoints: 13
   test_path: ./datasets/coco_val_single_pose
   quantization_path: ./datasets/coco_train_single_pose
   quantization_split: 0.3

training:
   batch_size: 32

preprocessing:
   rescaling:
      scale: 1/127.5
      offset: -1
   resizing:
      aspect_ratio: fit
      interpolation: nearest
   color_mode: rgb

postprocessing:
   kpts_conf_thresh: 0.15
   # confidence_thresh: 0.001
   # NMS_thresh: 0.1
   # plot_metrics: true
   # max_detection_boxes: 100

quantization:
   quantizer: TFlite_converter  # onnx_quantizer
   quantization_type: PTQ
   quantization_input_type: uint8
   quantization_output_type: float
   export_dir: quantized_models

tools:
   stedgeai:
      version: 10.0.0
      optimization: balanced
      on_cloud: True
      path_to_stedgeai: C:/Users/<XXXXX>/STM32Cube/Repository/Packs/STMicroelectronics/X-CUBE-AI/<*.*.*>/Utilities/windows/stedgeai.exe
   path_to_cubeIDE: C:/ST/STM32CubeIDE_<*.*.*>/STM32CubeIDE/stm32cubeide.exe

benchmarking:
   board: STM32H747I-DISCO

mlflow:
   uri: ./src/experiments_outputs/mlruns

hydra:
   run:
      dir: ./src/experiments_outputs/${now:%Y_%m_%d_%H_%M_%S}