general:
  project_name: imagenet
  model_path: ../../stm32ai-modelzoo/image_classification/efficientnetv2/Public_pretrainedmodel_public_dataset/ImageNet/efficientnet_v2B3_300/efficientnet_v2B3_300.h5
  logs_dir: logs
  saved_models_dir: saved_models
  display_figures: false
  global_seed: 127
  gpu_memory_limit: 24
  num_threads_tflite: 12

operation_mode: chain_eqeb

dataset:
  name: imagenet
  class_names: 
  test_path: "/local/datasets/ic_imagenet_2012/validation/"
  quantization_path: "/local/datasets/ic_imagenet_2012/quantization/"
  quantization_split: 0.001

preprocessing:
  rescaling: { scale: 1/127.5, offset: -1 }
  resizing:
    interpolation: nearest
    aspect_ratio: fit
  color_mode: rgb

quantization:
  quantizer: TFlite_converter
  quantization_type: PTQ
  quantization_input_type: uint8
  quantization_output_type: float
  export_dir: quantized_models

tools:
   stedgeai:
      version: 10.0.0
      optimization: balanced
      on_cloud: True
      path_to_stedgeai: C:/Users/<XXXXX>/STM32Cube/Repository/Packs/STMicroelectronics/X-CUBE-AI/<*.*.*>/Utilities/windows/stedgeai.exe
   path_to_cubeIDE: C:/ST/STM32CubeIDE_<*.*.*>/STM32CubeIDE/stm32cubeide.exe

benchmarking:
   board: STM32N6570-DK

mlflow:
  uri: ./src/experiments_outputs/mlruns

hydra:
  run:
    dir: ./src/experiments_outputs/${now:%Y_%m_%d_%H_%M_%S}

