general:
  project_name: coco_instance_seg
  model_path: https://github.com/stm32-hotspot/ultralytics/raw/refs/heads/main/examples/YOLOv8-STEdgeAI/stedgeai_models/segmentation/yolov8n_256_quant_pc_ii_seg_coco-st.tflite
  model_type: yolo_v8_seg
  display_figures: true

operation_mode: prediction

dataset:
  name: COCO
  classes_file_path : ../datasets/coco_classes.txt
  class_names: 

preprocessing:
  rescaling:
    scale: 1/255.0
    offset: 0
  resizing:
    interpolation: bilinear
    aspect_ratio: fit
  color_mode: rgb

postprocessing:
  confidence_thresh: 0.6
  IoU_eval_thresh: 0.4

prediction:
  test_files_path: ./datasets/coco/images

mlflow:
  uri: ./src/experiments_outputs/mlruns

hydra:
   run:
      dir: ./src/experiments_outputs/${now:%Y_%m_%d_%H_%M_%S}