operation_mode: chain_eqe

general:
  display_figures: false

model:
  framework: 'torch' # Must have
  model_name: 'mobilenetb_a025_pt'
  # model_path: with .pt file we require model_name as well
  pretrained: true
  pretrained_dataset: "imagenet"
  input_shape: [3, 224, 224]

quantization:
  quantizer: Onnx_quantizer
  quantization_type: PTQ
  quantization_input_type: uint8
  quantization_output_type: float
  export_dir: quantized_models

dataset:
  dataset_name: "imagenet" # options "flowers102", "food101", "imagenet"
  class_names: ''
  classes_file_path: ./datasets/deployment_labels_imagenet.txt
  data_dir: '/local/datasets/ic_imagenet_2012' # provide full path the dataset, this can also be used to quantization
  num_classes: 1000 # change according to your dataset
  train_split: "train"
  val_split: "validation"
  quantization_split: 0.01
  # test_path: you can provide path to test data and it will be used for validation
  # quantization_path: this will be used for quantization otherwise training data will be used
  workers: 4
  no_prefetcher: true

preprocessing: 
  rescaling: # Not used for Torch Image Classification
    scale: None # Not used for Torch Image Classification
    offset: None # Not used for Torch Image Classification
  resizing:
    interpolation: random # 'random' means random.choice(["bilinear", "bicubic"]). This will be used for training data and bilinear is fixed for test data 
    aspect_ratio: fit # fit is the only aspect_ratio supported for torch image classification.
  color_mode: rgb # rgb is the only color_mode supported  for torch image classification.
  normalization:
    mean: [0.485, 0.456, 0.406] # Subtracted from each channel: (x - mean) / std
    std: [0.229, 0.224, 0.225] # Divides each channel after mean subtraction

mlflow:
  uri: ./pt/src/experiments_outputs/mlruns

hydra:
  run:
    dir: ./pt/src/experiments_outputs/${now:%Y_%m_%d_%H_%M_%S}
