general:
  project_name: plant-village
  logs_dir: logs
  saved_models_dir: saved_models
  display_figures: true
  global_seed: 127
  gpu_memory_limit: 36
operation_mode: chain_tbqeb
dataset:
  name: plant-village
  class_names:
  - Apple___Apple_scab
  - Apple___Black_rot
  - Apple___Cedar_apple_rust
  - Apple___healthy
  - Background_without_leaves
  - Blueberry___healthy
  - Cherry___healthy
  - Cherry___Powdery_mildew
  - Corn___Cercospora_leaf_spot Gray_leaf_spot
  - Corn___Common_rust
  - Corn___healthy
  - Corn___Northern_Leaf_Blight
  - Grape___Black_rot
  - Grape___Esca_(Black_Measles)
  - Grape___healthy
  - Grape___Leaf_blight_(Isariopsis_Leaf_Spot)
  - Orange___Haunglongbing_(Citrus_greening)
  - Peach___Bacterial_spot
  - Peach___healthy
  - Pepper,_bell___Bacterial_spot
  - Pepper,_bell___healthy
  - Potato___Early_blight
  - Potato___healthy
  - Potato___Late_blight
  - Raspberry___healthy
  - Soybean___healthy
  - Squash___Powdery_mildew
  - Strawberry___healthy
  - Strawberry___Leaf_scorch
  - Tomato___Bacterial_spot
  - Tomato___Early_blight
  - Tomato___healthy
  - Tomato___Late_blight
  - Tomato___Leaf_Mold
  - Tomato___Septoria_leaf_spot
  - Tomato___Spider_mites Two-spotted_spider_mite
  - Tomato___Target_Spot
  - Tomato___Tomato_mosaic_virus
  - Tomato___Tomato_Yellow_Leaf_Curl_Virus
  training_path: ./datasets/Plant_leave_diseases_dataset_without_augmentation
  validation_path: null
  validation_split: 0.2
  test_path: null
  quantization_path: null
  quantization_split: null
  check_image_files: false
  seed: 127
preprocessing:
  rescaling:
    scale: 1/127.5
    offset: -1
  resizing:
    interpolation: nearest
    aspect_ratio: fit
  color_mode: rgb
data_augmentation:
  random_jpeg_quality:
    jpeg_quality: (60, 100)
    change_rate: 0.2
  random_posterize:
    bits: (4, 8)
    change_rate: 0.15
  random_hue:
    delta: 0.05
    change_rate: 1.0
  random_contrast:
    factor: 0.6
  random_brightness:
    factor: 0.05
  random_flip:
    mode: horizontal
  random_rectangle_erasing:
    nrec: (0, 10)
    area: (0.0, 0.1)
    wh_ratio: (0.25, 4.0)
    fill_method: mosaic
    mode: batch
  random_translation:
    width_factor: 0.25
    height_factor: 0.25
    fill_mode: reflect
    interpolation: nearest
  random_rotation:
    factor: 0.125
    fill_mode: reflect
    interpolation: nearest
  random_zoom:
    width_factor: 0.25
    height_factor: 0.25
    fill_mode: reflect
    interpolation: nearest
  random_shear:
    factor: 0.15
    fill_mode: wrap
    interpolation: nearest
training:
  model:
    name: fdmobilenet
    alpha: 0.25
    input_shape: (128, 128, 3)
  frozen_layers: None
  dropout: 0.3
  batch_size: 128
  epochs: 1000
  optimizer:
    Adam:
      learning_rate: 0.01
  callbacks:
    ReduceLROnPlateau:
      monitor: val_accuracy
      mode: max
      factor: 0.5
      patience: 60
      min_lr: 1.0e-05
    EarlyStopping:
      monitor: val_accuracy
      mode: max
      restore_best_weights: true
      patience: 80
quantization:
  quantizer: TFlite_converter
  quantization_type: PTQ
  quantization_input_type: uint8
  quantization_output_type: float
  export_dir: quantized_models
tools:
  stedgeai:
    version: 10.0.0
    optimization: balanced
    on_cloud: True
    path_to_stedgeai: C:/Users/<XXXXX>/STM32Cube/Repository/Packs/STMicroelectronics/X-CUBE-AI/<*.*.*>/Utilities/windows/stedgeai.exe
  path_to_cubeIDE: C:/ST/STM32CubeIDE_<*.*.*>/STM32CubeIDE/stm32cubeide.exe
benchmarking:
  board: STM32H747I-DISCO
deployment:
  c_project_path: ../../application_code/image_classification/
  IDE: GCC
  verbosity: 1
  hardware_setup:
    serie: STM32H7
    board: STM32H747I-DISCO
    input: CAMERA_INTERFACE_DCMI
    output: DISPLAY_INTERFACE_USB
mlflow:
  uri: ./experiments_outputs/mlruns
hydra:
   run:
      dir: ./experiments_outputs/${now:%Y_%m_%d_%H_%M_%S}
