general:
  project_name: st_yololcv1_192_onnx
  gpu_memory_limit: 16
  num_threads_tflite: 12
  global_seed: 127

model:
  model_path: ../../stm32ai-modelzoo/object_detection/st_yololcv1/ST_pretrainedmodel_public_dataset/coco_2017_person/st_yololcv1_192/st_yololcv1_192.keras
  model_type: st_yololcv1
  input_shape: (192,192,3)

operation_mode: chain_eqe

dataset:
  dataset_name: coco
  format: tfs
  class_names:
  - person
  train_images_path: /local/data/od_coco_2017_person/train
  train_annotations_path: /local/data/od_coco_2017_person/train
  test_images_path: /local/data/od_coco_2017_person/test
  test_annotations_path: /local/data/od_coco_2017_person/test
  quantization_split: 0.001

preprocessing:
  rescaling:
    scale: 1/255
    offset: 0
  resizing:
    aspect_ratio: fit
    interpolation: nearest
  color_mode: rgb
  
postprocessing:
  confidence_thresh: 0.001
  NMS_thresh: 0.5
  IoU_eval_thresh: 0.5
  plot_metrics: false
  max_detection_boxes: 100

quantization:
  quantizer: onnx_quantizer
  granularity: per_channel
  target_opset: 21
  quantization_type: PTQ
  quantization_input_type: uint8
  quantization_output_type: float
  export_dir: quantized_models
  onnx_extra_options:
    WeightSymmetric: True
    ActivationSymmetric: False
    QuantizeBias: True
    CalibMovingAverage: True
    
mlflow:
  uri: ./tf/src/experiments_outputs/mlruns

hydra:
   run:
      dir: ./tf/src/experiments_outputs/${now:%Y_%m_%d_%H_%M_%S}